# Generated by Django 4.1.2 on 2022-11-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdata',
            name='type',
            field=models.CharField(max_length=5, verbose_name='Название категории'),
        ),
    ]
