# Generated by Django 4.1.2 on 2022-10-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_alter_user_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Электронный адрес'),
        ),
    ]
