# Generated by Django 4.1.2 on 2022-11-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Все товары', 'Все товары'), ('Верхняя одежда', 'Верхняя одежда'), ('Футболки', 'Футболки'), ('Толстовки', 'Толстовки'), ('Штаны', 'Штаны'), ('Аксессуары', 'Аксессуары')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('L', 'L'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Мужская', 'Мужская'), ('Женская', 'Женская'), ('Детская', 'Детская')], max_length=15, verbose_name='Тип одежды'),
        ),
    ]
