# Generated by Django 4.1.2 on 2022-10-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_sellerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.IntegerField(null=True, verbose_name='Номер квартиры'),
        ),
    ]
