# Generated by Django 4.1.2 on 2022-11-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_alter_product_category_alter_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='app_shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth_order', to='app_shop.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth_product', to='app_shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, related_name='access', to='app_shop.rightaccess', verbose_name='Права'),
        ),
        migrations.AlterModelTable(
            name='productorder',
            table=None,
        ),
    ]
