# Generated by Django 4.1.2 on 2022-10-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_alter_address_apartment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdata',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True, verbose_name='Электронный адрес организации'),
        ),
    ]
