# Generated by Django 4.1.2 on 2022-12-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
