# Generated by Django 4.1.2 on 2022-12-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0008_remove_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='price',
            field=models.FloatField(default=5000, verbose_name='Цена товара'),
            preserve_default=False,
        ),
    ]
