# Generated by Django 4.1.2 on 2022-10-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0009_alter_user_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdata',
            name='reg_date',
            field=models.DateField(null=True, verbose_name='Дата регистрации организации'),
        ),
    ]
