# Generated by Django 4.1.2 on 2022-12-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0009_productorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст отзыва'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
