# Generated by Django 4.1.2 on 2022-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0010_alter_address_apartment_number_alter_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('0', 'created'), ('1', 'paid'), ('2', 'confirmed'), ('3', 'delivered')], verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество на складе'),
        ),
    ]
