# Generated by Django 4.1.2 on 2022-12-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0011_alter_order_status_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerdata',
            options={'verbose_name': 'Данные продавца', 'verbose_name_plural': 'Данные продавцов'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'created'), (1, 'paid'), (2, 'confirmed'), (3, 'delivered')], verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Все товары', 'All'), ('Верхняя одежда', 'Outerwear'), ('Футболки', 'Shirts'), ('Толстовки', 'Hoodies'), ('Штаны', 'Pants'), ('Аксессуары', 'Accessories')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Xs'), ('S', 'S'), ('L', 'L'), ('M', 'M'), ('XL', 'Xl'), ('XXL', 'Xxl')], max_length=3, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Мужская', 'Men'), ('Женская', 'Woman'), ('Детская', 'Child')], max_length=15, verbose_name='Тип одежды'),
        ),
    ]
