services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - .env
    ports:
      - "5672:5672"
    expose:
      - 5672

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${DOCKER_POSTGRES_DB_HOST}
    depends_on:
      - db

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A djangoShop worker --loglevel=info
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${DOCKER_POSTGRES_DB_HOST}
    depends_on:
      - db
      - rabbitmq
